apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-py
  labels:
    app: ddns-py
spec:
  timeZone: "America/Fortaleza"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  schedule: "21  14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: "IMAGEM COM TAG"
            name: ddns-py
            envFrom:
            - configMapRef:
                name: "ddns-py"
            - secretRef:
                name: "ddns-py"           
            imagePullPolicy: Always
          restartPolicy: OnFailure
  